### ISSUE TITLE
Generating polygon on re-centered Winkel-Tripel

### ISSUE THREAD

**Issue by MartinBeal** [wilkelab/practicalgg#2]
Using this handy [recenter function ](https://github.com/AustralianAntarcticDivision/SOmap/issues/34) I am able to recenter global spatial SF data to any desired meridian. 

However, it doesn't work with your solution for creating a [background oceans polygon](https://wilkelab.org/practicalgg/articles/Winkel_tripel.html). When projecting the object to Winkel-Tripel it folds on itself. 

![Rplot](https://user-images.githubusercontent.com/45400296/68077796-15a30a00-fdc2-11e9-8a3f-a3237214cafb.png)

Any idea how to do this for 360 degree data? 

`### My code
shift <- -152  # desired meridian shift

maxlong <- 180 + shift + 360  # shift 180 degrees to 360 degrees
minlong <- 180 + shift

longs <- c(rep(c(maxlong, minlong), each = 181), maxlong )

### Your code
outline <- 
  list(cbind(longs, lats)) %>%
  st_polygon() %>%
  st_sfc( # create sf geometry list column
    crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
  ) %>% 
  st_sf()

outline <- outline %>%   
  st_transform_proj(crs = crs_wintri) # transform to Winkel tripel

ggplot() + 
  geom_sf(
    data = outline,
    fill = "#56B4E950", color = "grey30", size = 0.5/.pt
  ) +
  coord_sf(datum = NULL) +
  theme_map()`

**Comment by clauswilke** [comment]
Please provide a complete reproducible example, prepared with the [reprex](https://reprex.tidyverse.org/articles/articles/magic-reprex.html) package.

**Comment by MartinBeal** [comment]
In fact, I later realized that the issue was merely to change the meridian in the projection with:

`
shift <- -152                               # desired meridian shift
central_meridian <- 360 + shift

proj <-  sprintf("+proj=wintri +datum=WGS84 +lon_0=%i +no_defs +over", central_meridian) 
`

Sorry to bother you. Thanks for the link to the reprex vignette, I will read up on that and use it in the future.
